"""Build small deterministic documentation assets from finished artifacts.

This script reads saved metrics and predictions only. It never fits, tunes, or
re-trains a model.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
FINAL = ROOT / "outputs" / "final_evaluation"


def _records(frame: pd.DataFrame) -> list[dict[str, object]]:
    return json.loads(frame.to_json(orient="records"))


def _probabilities(row: pd.Series) -> dict[str, float]:
    return {
        "away_win": round(float(row.p_A), 6),
        "draw": round(float(row.p_D), 6),
        "home_win": round(float(row.p_H), 6),
    }


def _markdown_table(frame: pd.DataFrame, formats: dict[str, str] | None = None) -> str:
    formats = formats or {}
    headers = [str(column) for column in frame.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in frame.itertuples(index=False, name=None):
        rendered = []
        for column, value in zip(frame.columns, row):
            if pd.isna(value):
                rendered.append("—")
            elif column in formats:
                rendered.append(formats[column].format(value))
            else:
                rendered.append(str(value))
        lines.append("| " + " | ".join(rendered) + " |")
    return "\n".join(lines)


def build_results() -> None:
    prematch_class = pd.read_csv(FINAL / "prematch_classification_metrics.csv")
    prematch_reg = pd.read_csv(FINAL / "prematch_regression_metrics.csv")
    snapshot_class = pd.read_csv(FINAL / "snapshot_classification_metrics.csv")
    snapshot_reg = pd.read_csv(FINAL / "snapshot_regression_metrics.csv")
    paired = pd.read_csv(FINAL / "paired_rps_differences_vs_market.csv")

    headline = {
        "model1_rf_platt_rps": float(
            prematch_class.query("model == 'random_forest' and method == 'platt'").iloc[0].rps
        ),
        "market_raw_rps": float(prematch_class.query("model == 'market' and method == 'raw'").iloc[0].rps),
        "model2_rf_mae": float(prematch_reg.query("model == 'random_forest'").iloc[0].mae),
        "model3_gb_raw_rps": float(
            snapshot_class.query("model == 'gradient_boosting' and method == 'raw'").iloc[0].rps
        ),
        "model3_xgb_mae": float(snapshot_reg.query("model == 'xgboost'").iloc[0].mae),
        "final_matches": int(prematch_class.n_matches.max()),
        "final_snapshots": int(snapshot_class.n_snapshots.max()),
    }
    data_dir = DOCS / "assets" / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "results-summary.json").write_text(
        json.dumps(headline, indent=2) + "\n", encoding="utf-8"
    )

    m1 = prematch_class[
        prematch_class.model.isin(["random_forest", "gradient_boosting", "xgboost", "scratch_figs", "market"])
    ][["model", "method", "rps", "rps_ci_lower", "rps_ci_upper", "log_loss", "brier", "ece", "accuracy"]]
    m2 = prematch_reg[
        prematch_reg.model.isin(["random_forest", "gradient_boosting", "xgboost", "scratch_figs"])
    ][["model", "mae", "mae_ci_lower", "mae_ci_upper", "rmse", "correlation", "converted_rps"]]
    m3c = snapshot_class[
        snapshot_class.model.isin(
            ["gradient_boosting", "xgboost", "random_forest", "scratch_figs", "frozen_market", "frozen_best_prematch"]
        )
    ][["model", "method", "rps", "rps_ci_lower", "rps_ci_upper", "log_loss", "ece"]]
    m3r = snapshot_reg[
        snapshot_reg.model.isin(["xgboost", "gradient_boosting", "random_forest", "scratch_figs"])
    ][["model", "mae", "rmse", "correlation", "converted_rps"]]
    comparison = paired.query("model == 'random_forest' and method == 'platt'")[[
        "mean_rps_difference_vs_raw_market", "ci_lower", "ci_upper"
    ]]
    formats = {column: "{:.3f}" for column in set(m1.columns) | set(m2.columns) | set(m3c.columns) | set(m3r.columns)}
    formats.pop("model", None)
    formats.pop("method", None)
    generated = "\n".join(
        [
            "<!-- Generated by scripts/build_docs_data.py; do not edit manually. -->",
            "## Model 1 — pre-match classification",
            "",
            _markdown_table(m1, formats),
            "",
            "## Model 2 — pre-match signed margin",
            "",
            _markdown_table(m2, formats),
            "",
            "## Model 3 — in-play outcome",
            "",
            _markdown_table(m3c, formats),
            "",
            "## Model 3 — in-play signed margin",
            "",
            _markdown_table(m3r, formats),
            "",
            "## Paired Model 1 comparison with the raw market",
            "",
            _markdown_table(comparison, formats),
            "",
        ]
    )
    results_dir = DOCS / "results"
    results_dir.mkdir(parents=True, exist_ok=True)
    (results_dir / "generated_metrics.md").write_text(generated, encoding="utf-8")


def build_demo() -> None:
    prematch = pd.read_parquet(ROOT / "outputs" / "features" / "prematch_features.parquet")
    snapshots = pd.read_parquet(ROOT / "outputs" / "snapshots" / "snapshot_features.parquet")
    class_predictions = pd.read_parquet(FINAL / "snapshot_classification_predictions.parquet")
    margin_predictions = pd.read_parquet(FINAL / "snapshot_regression_predictions.parquet")
    prematch_class = pd.read_csv(FINAL / "prematch_classification_predictions.csv")
    prematch_margin = pd.read_csv(FINAL / "prematch_regression_predictions.csv")

    metadata = prematch[prematch.split_role.eq("final_test")][
        ["match_id", "clean_date", "home_team", "away_team", "split_role"]
    ].copy()
    raw = class_predictions.query("model == 'gradient_boosting' and method == 'raw'")
    calibrated = class_predictions.query("model == 'gradient_boosting' and method == 'platt'")[
        ["match_id", "snapshot_minute", "p_A", "p_D", "p_H"]
    ].rename(columns={"p_A": "cal_p_A", "p_D": "cal_p_D", "p_H": "cal_p_H"})
    margin = margin_predictions.query("model == 'xgboost'")[
        ["match_id", "snapshot_minute", "predicted_margin"]
    ]
    score = snapshots[snapshots.split_role.eq("final_test")][
        ["match_id", "snapshot_minute", "home_score", "away_score"]
    ]
    timeline = raw.merge(calibrated, on=["match_id", "snapshot_minute"], validate="one_to_one")
    timeline = timeline.merge(margin, on=["match_id", "snapshot_minute"], validate="one_to_one")
    timeline = timeline.merge(score, on=["match_id", "snapshot_minute"], validate="one_to_one")
    pm_class = prematch_class.query("model == 'random_forest' and method == 'platt'")
    pm_margin = prematch_margin.query("model == 'random_forest'")

    matches = []
    for item in metadata.sort_values(["clean_date", "match_id"]).itertuples(index=False):
        match_id = int(item.match_id)
        class_row = pm_class[pm_class.match_id.eq(match_id)].iloc[0]
        margin_row = pm_margin[pm_margin.match_id.eq(match_id)].iloc[0]
        points = []
        for row in timeline[timeline.match_id.eq(match_id)].sort_values("snapshot_minute").itertuples(index=False):
            points.append(
                {
                    "minute": int(row.snapshot_minute),
                    "score": {"home": int(row.home_score), "away": int(row.away_score)},
                    "probabilities": {
                        "away_win": round(float(row.p_A), 6),
                        "draw": round(float(row.p_D), 6),
                        "home_win": round(float(row.p_H), 6),
                    },
                    "calibrated_probabilities": {
                        "away_win": round(float(row.cal_p_A), 6),
                        "draw": round(float(row.cal_p_D), 6),
                        "home_win": round(float(row.cal_p_H), 6),
                    },
                    "expected_final_margin": round(float(row.predicted_margin), 6),
                }
            )
        matches.append(
            {
                "match_id": match_id,
                "date": pd.Timestamp(item.clean_date).date().isoformat(),
                "home_team": str(item.home_team),
                "away_team": str(item.away_team),
                "split": str(item.split_role),
                "prematch": {
                    "probabilities": _probabilities(class_row),
                    "expected_goal_margin": round(float(margin_row.predicted_margin), 6),
                },
                "timeline": points,
            }
        )
    payload = {
        "label": "Static demonstration using saved held-out predictions",
        "historical_backtest": True,
        "live_inference": False,
        "class_order": ["away_win", "draw", "home_win"],
        "snapshot_boundary": "event_seconds_exact <= snapshot_seconds",
        "matches": matches,
    }
    (DOCS / "assets" / "data" / "demo-matches.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def copy_assets() -> None:
    assets = {
        "outputs/figures/p1/p1_example_multilayer_network.png": "assets/images/p1/example_multilayer_network.png",
        "outputs/figures/p1/p1_team_zone_comparison.png": "assets/images/p1/team_zone_comparison.png",
        "outputs/figures/p1/p1_orientation_validation.png": "assets/images/p1/orientation_validation.png",
        "outputs/figures/final/final_model1_rps.png": "assets/images/results/model1_rps.png",
        "outputs/figures/final/final_model2_mae.png": "assets/images/results/model2_mae.png",
        "outputs/figures/final/final_model3_rps_by_minute.png": "assets/images/results/model3_rps_by_minute.png",
        "outputs/figures/models/model1_reliability.png": "assets/images/results/model1_reliability.png",
        "outputs/figures/models/figs_split_budget.png": "assets/images/results/figs_split_budget.png",
        "outputs/figures/models/kernel_scaling.png": "assets/images/results/kernel_scaling.png",
        "outputs/figures/explainability/prematch_classification_random_forest_global_shap.png": "assets/images/explainability/model1_global_shap.png",
        "outputs/figures/explainability/full_match_explanation_timeline.png": "assets/images/explainability/full_match_timeline.png",
        "report/final_report.pdf": "assets/report/final_report.pdf",
    }
    for source, destination in assets.items():
        target = DOCS / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / source, target)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Rebuild and fail if tracked generated assets change (intended for clean CI checkouts).",
    )
    args = parser.parse_args()
    build_results()
    build_demo()
    copy_assets()
    if args.check:
        print("Documentation data rebuilt; use git diff --exit-code to verify synchronization.")
    else:
        print("Built documentation tables, static replay data, figures, and report assets.")


if __name__ == "__main__":
    main()
